# Generated by Django 6.1.1 on 2026-09-24 06:02

from django.db import migrations, models

import apps.ICmanage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rx', 'Rx IC'), ('charger', 'Charger IC')], max_length=7, verbose_name='類型')),
                ('code', models.SlugField(default=apps.ICmanage.models.ic_code, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='設定名稱')),
                ('model_number', models.CharField(max_length=120, verbose_name='IC 型號')),
                ('mode', models.CharField(choices=[('curve', '資料庫曲線查表'), ('fixed', '自訂固定效率')], default='curve', max_length=5, verbose_name='效率來源')),
                ('axis', models.CharField(choices=[('power', '輸出功率 (W)'), ('current', '充電電流 (A)')], default='current', max_length=7, verbose_name='查表軸向')),
                ('efficiency', models.FloatField(blank=True, null=True, verbose_name='固定效率 (%)')),
                ('points', models.JSONField(blank=True, default=list, verbose_name='曲線資料點')),
                ('provisional', models.BooleanField(default=True, verbose_name='暫定數據（尚未驗證）')),
                ('source', models.CharField(blank=True, max_length=500, verbose_name='資料來源／量測條件')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='unique_ic_setting_name')],
            },
        ),
    ]
