# Generated by Django 6.1.1 on 2026-09-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seed_ic_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icsetting',
            options={'ordering': ('kind', 'name')},
        ),
    ]
